### ISSUE TITLE
RFC: `riemann-domain-check` to monitor domain name expiration date

### ISSUE THREAD

**Issue by smortex** [riemann/riemann-tools#249]
## Issue

We currently have no tooling to check if a domain name is about to expire.  While `whois(1)` is ubiquitous to query information about a domain, the format is not standardized and parsing the output is tedious. But good news everyone, [Registration Data Access Protocol (RDAP)](https://www.icann.org/rdap) will (maybe) change that!

This seems a quite trivial tool to build: there is a [rdap](https://rubygems.org/gems/rdap) gem available, and the `riemann-domain-check` tool could accept a list of domains to check, a warning and a critical thresholds in day (e.g. 30, 7) and output metrics like:

```yaml
service: example.com expiration date
metric: 1668968347
state: warning
description: Domain expire in 30 days
```

Should `riemann-domain-check` be part of `riemann-tools` or should it be a side project?

### What's your riemann-tools version?

n/a

### What platform are you on?

n/a
